03/08/2022 14:25:30|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
03/08/2022 14:28:59|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
03/08/2022 14:30:02|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
03/08/2022 14:32:40|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
03/08/2022 14:33:29|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
03/08/2022 14:37:47|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
03/08/2022 14:37:47|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
03/08/2022 14:37:47|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
03/08/2022 14:37:47|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
03/08/2022 14:37:47|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
03/08/2022 14:40:57|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232f5eb20>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:41:16|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232f64640>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:41:36|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 15:41, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232f102e0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 14:42:12|INFO    |root                            |BAZARR throttled providers have been reset.|
03/08/2022 14:42:26|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232dbe430>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:42:40|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Better+Call+Saul+S06E11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232a0db20>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:42:45|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa2406a1e80>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:42:59|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Better+Call+Saul+S06E11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232a0daf0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:43:04|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 15:43, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232dcb3d0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 14:43:18|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 15:43, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Better+Call+Saul+S06E11 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa232a128b0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 14:47:17|INFO    |root                            |Bazarr is being restarted...|
03/08/2022 14:47:33|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
03/08/2022 14:47:33|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
03/08/2022 14:47:33|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
03/08/2022 14:47:33|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
03/08/2022 14:47:33|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
03/08/2022 14:49:21|INFO    |root                            |Throttling opensubtitles for 10 minutes, until 22/08/03 14:59, because of: Unauthorized. Exception info: None|
03/08/2022 14:50:03|INFO    |root                            |BAZARR throttled providers have been reset.|
03/08/2022 14:50:17|INFO    |root                            |Throttling opensubtitles for 10 minutes, until 22/08/03 15:00, because of: Unauthorized. Exception info: None|
03/08/2022 14:50:22|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea525dfa0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:50:41|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea52ae400>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:51:00|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 15:51, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea525d4f0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 14:53:32|INFO    |root                            |BAZARR throttled providers have been reset.|
03/08/2022 14:56:15|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea66a2310>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:56:34|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea532e130>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 14:56:53|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 15:56, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea45f9fa0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 15:29:24|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subtitulamos.tv', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 15:29:24|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 15:48:42|INFO    |root                            |Throttling subscene for 10 minutes, until 22/08/03 15:58, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'|
03/08/2022 15:48:52|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 15:49:19|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subtitulamos.tv', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 15:49:39|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 15:49:39|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subtitulamos.tv', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 15:56:49|INFO    |root                            |BAZARR throttled providers have been reset.|
03/08/2022 15:57:07|INFO    |root                            |Throttling subscene for 10 minutes, until 22/08/03 16:07, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'|
03/08/2022 15:57:17|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea4615190>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 15:57:36|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feead46fd60>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 15:57:55|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 16:57, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E05 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea4330460>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 16:02:48|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 17:34:57|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
03/08/2022 17:34:57|INFO    |root                            |Using subscene again after 10 minutes, (disabled because: ProviderError)|
03/08/2022 17:35:07|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 17:35:11|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea431bc40>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 17:35:17|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subdivx.com', port=443): Read timed out. (read timeout=20), retrying in 5 seconds...|
03/08/2022 17:35:30|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea45d8af0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 17:35:49|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 18:35, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea50fc640>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 17:37:01|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subtitulamos.tv', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 17:46:37|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
03/08/2022 17:50:51|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
03/08/2022 17:52:33|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
03/08/2022 18:36:16|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
03/08/2022 18:36:30|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea21d06a0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 18:36:49|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea364e2e0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 18:37:08|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 19:37, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea4d2df40>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 19:10:26|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
03/08/2022 20:34:57|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
03/08/2022 20:35:08|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 20:35:12|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea43235e0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 20:35:18|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subdivx.com', port=443): Read timed out. (read timeout=20), retrying in 5 seconds...|
03/08/2022 20:35:31|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea4d562e0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 20:35:50|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 21:35, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea3e00f10>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 20:37:57|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subtitulamos.tv', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 20:38:05|WARNING |retry.api                       |HTTPSConnectionPool(host='subscene.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 20:46:11|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
03/08/2022 20:59:02|WARNING |retry.api                       |HTTPSConnectionPool(host='subscene.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 21:13:52|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 21:16:49|WARNING |retry.api                       |HTTPSConnectionPool(host='subscene.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 21:36:42|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
03/08/2022 21:36:57|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea29f14f0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 21:37:16|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea2527100>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 21:37:35|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/03 22:37, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Miss+Kobayashi%27s+Dragon+Maid+S01E09 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea274f8e0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 21:45:20|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
03/08/2022 21:46:26|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
03/08/2022 21:47:33|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
03/08/2022 21:48:40|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
03/08/2022 21:49:47|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
03/08/2022 21:50:54|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
03/08/2022 21:52:01|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
03/08/2022 21:53:11|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
03/08/2022 21:54:18|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
03/08/2022 21:55:25|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
03/08/2022 21:56:32|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
03/08/2022 21:57:38|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
03/08/2022 21:58:36|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
03/08/2022 23:34:57|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
03/08/2022 23:35:07|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 23:35:12|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea2a01340>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 23:35:17|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subdivx.com', port=443): Read timed out. (read timeout=20), retrying in 5 seconds...|
03/08/2022 23:35:31|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea44b3af0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
03/08/2022 23:35:50|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/04 00:35, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Steins%3BGate+S01E01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feea26036a0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
03/08/2022 23:37:56|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subtitulamos.tv', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 23:38:04|WARNING |retry.api                       |HTTPSConnectionPool(host='subscene.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
03/08/2022 23:46:10|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
03/08/2022 23:59:03|WARNING |retry.api                       |HTTPSConnectionPool(host='subscene.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
